name: guarded_go_router
description: guarded_go_router
version: 0.0.1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^7.1.1
  hooks_riverpod: ^2.1.3
  uni_links: ^0.5.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  mocktail: ^0.3.0

flutter:
