name: Run Tests

on:
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup FVM
        uses: leoafarias/fvm-action@v2
        with:
          version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
